# -*- coding: utf-8 -*-
"""Atividade_pyvis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OpIZz8Bjz7e2l6LrFyCD4TTaapXtmd6S
"""

!pip install pyvis

import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd
from pyvis.network import Network
from IPython.core.display import display, HTML

df = pd.read_csv("data/actorfilms.csv", usecols = [ "Actor" , "Film", "Year"])
df = df.sort_values(by="Year", ascending=False).head(3000) 
print(df)

g1 = Network(height="400px", width="70%", bgcolor="#222222", font_color="white", notebook=True, cdn_resources='in_line',directed = True, select_menu=True)
g1.barnes_hut()
df['Year'] = df['Year']/5000
sources = df['Actor']
targets = df['Film']
weights = df['Year']

edge_data = zip(sources, targets, weights)

for e in edge_data:
                src = e[0]
                dst = e[1]
                w = e[2]

                g1.add_node(src, src, title=src)
                g1.add_node(dst, dst, title=dst)
                g1.add_edge(src, dst, value=w)

neighbor_map = g1.get_adj_list()
for node in g1.nodes:
                node["title"] += " Neighbors:<br>" + "<br>".join(neighbor_map[node["id"]])
                node["value"] = len(neighbor_map[node["id"]])

g1.show_buttons(filter_=['physics'])
g1.show('example.html')
display(HTML('example.html'))
